### ISSUE TITLE
Question: Skipping of unlicensed objects

### ISSUE THREAD

**Issue by AR101** [tegosGroup/NAVToGit#38]
The exception configuration for objectranges is valuable and needed, but how does the tool behave if an unlicensed object is not in that config and not licensed?
Does finsql.exe simply hang, never finishing the export?

I am asking, because the [Export-NavApplicationObject](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/export-navapplicationobject?view=businesscentral-ps) CmdLet has a switch "ExportTxtSkipUnlicensed" handling that issue.

**Comment by swortmann** [comment]
Sorry about the late feedback:

In the case of unlicensed objects during the export, the finsql would simply stop and not finish the export (for that object type) at all. By design we are not using the PowerShell Cmdlets because they are only available, if I remember correctly, for NAV10+ and we want to support all other versions, too.
So to sum it up, when there is an unlicensed object which is not specified in the object ranges, the script will give you an error and you need to further specify the ranges.

**Comment by AR101** [comment]
If there is an error message that is at least clear for the user then.

So are you saying, you are not using the CMDlets at all, or you just do not use the "ExportTxtSkipUnlicensed" switch?

**Comment by AR101** [comment]
> > So are you saying, you are not using the CMDlets at all, or you just do not use the "ExportTxtSkipUnlicensed" switch?
> 
> We are not using the Cmdlets at all.

Interesting, well ok.
I guess this can be closed then.

Thanks for feedback. 👍
